"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 24;
let altura = 1.86;
const nacionalidade = 'brasileira';
const colegas = ['joao', 'lucas', 'fernanda'];
const tecnologias = ['html', 'css', 'js'];
const notas = [7, 9, 5, 8];
const lista = ['Joao', false, 24];
let idadeDaAna = 25;
idadeDaAna = '25 anos';
let dadosApi;
dadosApi = true;
dadosApi = 10;
dadosApi = [1, 2, 3];
dadosApi = 'Joao';
